[package]
name = "prevue"
version = "0.3.0"
edition = "2024"
rust-version = "1.88"
authors = ["morugetsm <shouu6@gmail.com>"]
description = "An HTML templating engine that uses Vue's template syntax."
license = "MIT"
repository = "https://github.com/morugetsm/prevue"
readme = "README.md"
keywords = ["template", "html", "vue"]
categories = ["template-engine"]

[dependencies]
boa_ast = "0.21"
boa_engine = { version = "0.21", features = ["deser"] }
boa_parser = "0.21"
html5ever = "0.39.0"
markup5ever_rcdom = "0.39.0"
serde = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
thiserror = "2.0"
